# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.DotNet.Runtime.9.x64
PackageVersion: 9.0.19
MinimumOSVersion: 10.0.21277.0
InstallerType: burn
Scope: machine
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  Custom: /norestart
ProductCode: '{2e2a622b-26b6-4d9b-9729-6a7c41311080}'
ReleaseDate: 2026-08-11
AppsAndFeaturesEntries:
- DisplayName: Microsoft .NET Runtime - 9.0.19 (x64)
  DisplayVersion: 9.0.19.36317
  ProductCode: '{D7D0F26F-6C69-4962-8104-3FB03A7D6699}'
  UpgradeCode: '{246F1645-53A5-57B7-A2FD-41078EF81F4D}'
Installers:
- Architecture: arm64
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/Runtime/9.0.19/dotnet-runtime-9.0.19-win-x64.exe
  InstallerSha256: 0213F4005607233F5FD565B3924B6587D195AD424B09FD7A9BF96162A6E0A2AA
ManifestType: installer
ManifestVersion: 1.12.0
