# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: IndexEducation.Pronote
PackageVersion: 2026.2.7
DefaultLocale: fr-FR
ManifestType: version
ManifestVersion: 1.28.0
