# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Microsoft.OneNote
PackageVersion: 16.0.20026.20112
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/
PublisherSupportUrl: https://support.office.com/
PrivacyUrl: https://privacy.microsoft.com/
Author: Microsoft Corporation
PackageName: Microsoft OneNote (Standalone)
PackageUrl: https://www.microsoft.com/microsoft-365/onenote/digital-note-taking-app
License: Proprietary (Freeware)
LicenseUrl: https://docs.microsoft.com/legal/termsofuse
Copyright: © Microsoft Corporation
CopyrightUrl: https://docs.microsoft.com/legal/termsofuse
ShortDescription: Your digital notebook for capturing and organizing everything across your devices. Jot down your ideas, keep track of classroom and meeting notes, clip from the web, or make a to-do list, as well as draw and sketch your ideas.
Moniker: onenote
Tags:
- microsoft-onenote
- microsoftonenote
- microsoft-one-note
- 1note
- digital-note-taking-app
- digitalnotetakingapp
- xpffzhvgqwwlhb
ManifestType: defaultLocale
ManifestVersion: 1.12.0