# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.AppInstaller.Preview
PackageVersion: 1.30.100
PackageLocale: nb
PackageName: Appinstallasjonsprogram (Forhåndsversjon)
ShortDescription: Forhåndsversjoner av Winget-ledetekstverktøyet.
Tags:
- appinstallasjonsprogram-forhåndsvisning
- microsoft-app-installer-preview
- microsoft-desktop-app-installer-preview
- pakkebehandling-for-windows-forhånd
- windows-package-manager-preview
- winget-cli-forhåndsversjon
- winget-forhåndsversjon
ManifestType: locale
ManifestVersion: 1.12.0
