# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: GrindingGearGames.PathOfExile2
PackageVersion: 0.5.5.61803
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.28.0
