# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Nvidia.Driver.GeForceGameReady
PackageVersion: '617.14'
PackageLocale: pl
PackageName: NVIDIA Sterownik GeForce Game Ready
PackageUrl: https://www.nvidia.com/pl-pl/drivers/
ManifestType: locale
ManifestVersion: 1.12.0
