# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Samsung.AutoDetectingSoftware
PackageVersion: 1.2.0.0
PackageLocale: en-US
Publisher: Samsung Electronics Co., Ltd.
PackageName: Auto-detecting Software
PackageUrl: https://www.samsung.com/global/galaxybooks-downloadcenter/
License: Freeware
ShortDescription: Compatibility layer for the "Detect your product" button on Samsung Download Center websites.
Moniker: samsung-auto-detect
Tags:
- auto-detect
- galaxy-book
- samsung
ManifestType: defaultLocale
ManifestVersion: 1.12.0
