# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.OneDrive
PackageVersion: 26.178.0913.0006
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /silent
  Upgrade: /update
ExpectedReturnCodes:
- InstallerReturnCode: 2147747474
  ReturnResponse: downgrade
- InstallerReturnCode: 2147747483
  ReturnResponse: packageInUse
- InstallerReturnCode: 2147747484
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 2147749059
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: OneDriveSetup.exe
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://oneclient.sfx.ms/Win/Installers/26.178.0913.0006/OneDriveSetup.exe
  InstallerSha256: 9FB250F008ABCF0E8D1F768853A2BE6B019B93895B5D1D798E5555640F3CA8DB
  ReleaseDate: 2026-09-26
- Architecture: x86
  Scope: machine
  InstallerUrl: https://oneclient.sfx.ms/Win/Installers/26.178.0913.0006/OneDriveSetup.exe
  InstallerSha256: 9FB250F008ABCF0E8D1F768853A2BE6B019B93895B5D1D798E5555640F3CA8DB
  InstallerSwitches:
    Custom: /allusers
  ReleaseDate: 2026-09-26
- Architecture: x64
  Scope: user
  InstallerUrl: https://oneclient.sfx.ms/Win/Installers/26.178.0913.0006/amd64/OneDriveSetup.exe
  InstallerSha256: 77B0CE5EDF1A2444E7695B79B74DCA9342D3278E89B36DA9A51799A1906EE5CF
  ReleaseDate: 2026-09-30
- Architecture: x64
  Scope: machine
  InstallerUrl: https://oneclient.sfx.ms/Win/Installers/26.178.0913.0006/amd64/OneDriveSetup.exe
  InstallerSha256: 77B0CE5EDF1A2444E7695B79B74DCA9342D3278E89B36DA9A51799A1906EE5CF
  InstallerSwitches:
    Custom: /allusers
  ReleaseDate: 2026-09-30
- Architecture: arm64
  Scope: user
  InstallerUrl: https://oneclient.sfx.ms/Win/Installers/26.178.0913.0006/arm64/OneDriveSetup.exe
  InstallerSha256: 5CC853DB444ABE85753F6058F173C98B9C12301E4F61198A60E8155D4EF607E4
  ReleaseDate: 2026-09-30
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://oneclient.sfx.ms/Win/Installers/26.178.0913.0006/arm64/OneDriveSetup.exe
  InstallerSha256: 5CC853DB444ABE85753F6058F173C98B9C12301E4F61198A60E8155D4EF607E4
  InstallerSwitches:
    Custom: /allusers
  ReleaseDate: 2026-09-30
ManifestType: installer
ManifestVersion: 1.28.0
