# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Gigaion.Airclone
PackageVersion: 0.23.1
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
ProductCode: '{A44FA56F-0F50-41B9-84FE-BE0085A5AF62}_is1'
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- ProductCode: '{A44FA56F-0F50-41B9-84FE-BE0085A5AF62}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/GigaionLLC/Airclone/releases/download/v0.23.1/airclone-setup-x64.exe
  InstallerSha256: FF3219652D441C0B2C53358CAEA489FBEB66AB06EB1FFECF677E82A49FF37951
  InstallerSwitches:
    Custom: /CURRENTUSER
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Airclone'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/GigaionLLC/Airclone/releases/download/v0.23.1/airclone-setup-x64.exe
  InstallerSha256: FF3219652D441C0B2C53358CAEA489FBEB66AB06EB1FFECF677E82A49FF37951
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Airclone'
ManifestType: installer
ManifestVersion: 1.28.0
