# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.VSTOR.LanguagePack.ko
PackageVersion: 10.0.60917
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /q /norestart
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VSTOR
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/4/a/e/4aed151e-5203-4e79-bc40-45ce7626d471/vstor40_LP_x86_kor.exe
  InstallerSha256: A587ABB3C061605003913A6144209F8E27CC865751A11A615A5CA03624A8FBE3
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/4/a/e/4aed151e-5203-4e79-bc40-45ce7626d471/vstor40_LP_x64_kor.exe
  InstallerSha256: D71653905FA7E5DD1B858EDAF0860EB10E7B683F9EF92281387BA175E2F99ADA
ExpectedReturnCodes:
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
ManifestType: installer
ManifestVersion: 1.28.0
