# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Microsoft.SystemCenter.MomADAdmin
PackageVersion: 10.25.10132.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.28.0
