# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nvidia.Driver.Studio.R580
PackageVersion: '581.57'
InstallerType: exe
InstallerSwitches:
  Silent: -s -n Display.Driver HDAudio.Driver
  SilentWithProgress: -s -n Display.Driver HDAudio.Driver
  Log: -log:"<LOGPATH>"
InstallerSuccessCodes:
- 1
ExpectedReturnCodes:
- InstallerReturnCode: 3858759936
  ReturnResponse: systemNotSupported
ElevationRequirement: elevationRequired
ReleaseDate: 2025-10-14
Installers:
- Architecture: x64
  InstallerUrl: https://uk.download.nvidia.com/Windows/581.57/581.57-desktop-win10-win11-64bit-international-nsd-dch-whql.exe
  InstallerSha256: D0934BE8E381BA29913C8D718F108232B2AC685F314CB02510672DEE3E746904
AppsAndFeaturesEntries:
- DisplayName: NVIDIA Graphics Driver 581.57
ManifestType: installer
ManifestVersion: 1.12.0
