# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Samsung.Magician
PackageVersion: 9.0.1.950
PackageLocale: en-US
Publisher: Samsung Electronics
PublisherUrl: https://semiconductor.samsung.com/
PublisherSupportUrl: https://semiconductor.samsung.com/consumer-storage/support/
PackageName: Samsung Magician
PackageUrl: https://semiconductor.samsung.com/consumer-storage/support/tools/
License: Proprietary
LicenseUrl: https://semiconductor.samsung.com/consumer-storage/support/tools/
Copyright: © . 2026 SAMSUNG ELECTRONICS CO., LTD. ALL RIGHTS RESERVED.
ShortDescription: Manages and monitors Samsung SSDs
Moniker: samsung-magician
ManifestType: defaultLocale
ManifestVersion: 1.12.0
