# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LaMotte.WaterLinkConnect
PackageVersion: 2.31.0.10
InstallerType: exe # InstallAware
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
  InstallLocation: TARGETDIR="<INSTALLPATH>"
  Log: /l="<LOGPATH>"
ProductCode: WaterLink Connect 2
ReleaseDate: 2026-03-16
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\WaterLink Connect 2'
Installers:
- Architecture: x86
  InstallerUrl: https://lamottesharedstorage.blob.core.windows.net/wlc-updates/WaterLinkConnect_2_31_0_10.exe
  InstallerSha256: 6AEDF84E3950F8250C49FB11C6B9C764A0556B2A92BF8B3EF13590D877FA7A1F
ManifestType: installer
ManifestVersion: 1.12.0
