# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WingFTPSoftware.WingFTPServer
PackageVersion: 8.2.3
InstallerType: inno
Scope: machine
InstallModes:
- interactive
ProductCode: '{DF494ADD-CA7F-445C-9D04-3F0CA3B8F20F}_is1'
ReleaseDate: 2026-08-24
AppsAndFeaturesEntries:
- ProductCode: '{DF494ADD-CA7F-445C-9D04-3F0CA3B8F20F}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Wing FTP Server'
Installers:
- Architecture: x64
  InstallerUrl: https://www.wftpserver.com/download/WingFtpServer.exe
  InstallerSha256: 44CE4DEE1ECF2894D8D48CDA64B0DD833D57CD711591FB000787390E0A8B3402
ManifestType: installer
ManifestVersion: 1.12.0
