# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Microsoft.Intune.DeviceInventory
PackageVersion: 26.8.34.2000
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Microsoft Device Inventory Agent
License: Proprietary
ShortDescription: Microsoft Device Inventory Agent
Moniker: microsoft-device-inventory-agent
Tags:
- device-inventory-agent
ManifestType: defaultLocale
ManifestVersion: 1.12.0
