# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Hanselman.WingetTUI
PackageVersion: 0.13.0
InstallerType: portable
UpgradeBehavior: uninstallPrevious
Commands:
- winget-tui
ReleaseDate: 2026-06-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/shanselman/winget-tui/releases/download/v0.13.0/winget-tui-x64.exe
  InstallerSha256: 074b48e15ea48123ffe27b51e256dbc9cff1a094c1496607dfb772c69fddc732
  AppsAndFeaturesEntries:
  - DisplayName: winget-tui (x64)
- Architecture: arm64
  InstallerUrl: https://github.com/shanselman/winget-tui/releases/download/v0.13.0/winget-tui-arm64.exe
  InstallerSha256: C34367D953E381DF6593C91F7867D79CDAC8114E2B5A78B8E2422EBD5C8DDA89
  AppsAndFeaturesEntries:
  - DisplayName: winget-tui (ARM64)
ManifestType: installer
ManifestVersion: 1.12.0
