# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Bluegrams.ScreenRuler
PackageVersion: 0.10.0
PackageLocale: en-US
Publisher: Bluegrams
PackageName: Screen Ruler
PackageUrl: https://sourceforge.net/projects/screenruler/
License: BSD-3
ShortDescription: A lightweight and configurable ruler tool for Windows Desktop. It allows you to measure the size of elements on the screen in different units, including pixels, centimeters and inches.
Moniker: screenruler
Tags:
- calibratable-ruler
- centimeter-ruler
- centimeterruler
- measurement-ruler
- measurementruler
- screen-ruler
- size-measuring
ManifestType: defaultLocale
ManifestVersion: 1.12.0
