# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: ModMii.ModMii
PackageVersion: 8.0.6
ReleaseDate: 2026-01-01
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ModMii.exe
  PortableCommandAlias: modmii
- RelativeFilePath: ModMiiSkin.exe
  PortableCommandAlias: modmiiskin
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/modmii/modmii.github.io/releases/download/8.0.6/ModMii.zip
  InstallerSha256: 7506717010913cf39e7e2302e7931186efbe080637059da3bba00e0242102148
ManifestType: installer
ManifestVersion: 1.28.0
