# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BegoniaHoldings.HopToDesk
PackageVersion: 1.46.55
Installers:
- Architecture: x86
  InstallerType: portable
  InstallerUrl: https://dl.hoptodesk.com/releases/1.46.55/HopToDesk.exe
  InstallerSha256: E5FD2B64DED8225654B5004B2B575F8B70B7A26E42760E4461C908E42715D706
  Commands:
  - hoptodesk
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://dl.hoptodesk.com/hoptodesk.msix
  InstallerSha256: CDD5C0BF0034E3667A14905458C2AA8E0A99B895370CDDACFB2AA5DB2D88A2D7
  SignatureSha256: C9744EA8AC89D9027D3F263510CCC2E741EFA2F87F1FF1820D7159B0A0BFC0EA
  UpgradeBehavior: install
  PackageFamilyName: HopToDesk.HopToDesk_ezfdsptqdsvtr
  RestrictedCapabilities:
  - runFullTrust
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/HopToDesk.HopToDesk_1.46.55.0_x64__ezfdsptqdsvtr'
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://dl.hoptodesk.com/releases/1.46.55/HopToDesk64.exe
  InstallerSha256: 71055C9C796A51303B48AB4639B9C19E11619AAA2057E30016317EBF6D723DD1
  Commands:
  - hoptodesk
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://dl.hoptodesk.com/hoptodesk-arm64.exe
  InstallerSha256: B131FFBC86D0465668D1A29C408A745B85FA8DA12D62EFB8C18C9C4674563F20
  Commands:
  - hoptodesk
ManifestType: installer
ManifestVersion: 1.12.0
