# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.VisualStudioCode
PackageVersion: 1.129.1
InstallerLocale: en-US
InstallerType: inno
InstallerSwitches:
  Custom: /mergetasks=!runcode
Commands:
- code
ReleaseDate: 2026-07-18
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/8a7abeba6e03ea3af87bfbce9a1b7e48fed567b8/VSCodeUserSetup-x64-1.129.1.exe
  InstallerSha256: bcbe938c145910cc42b80c73d8c987d959811b54987dfdef2f0c85fff3416878
  ProductCode: '{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Visual Studio Code (User)
    ProductCode: '{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Microsoft VS Code'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/8a7abeba6e03ea3af87bfbce9a1b7e48fed567b8/VSCodeSetup-x64-1.129.1.exe
  InstallerSha256: e3ad692a81d987deeacc0b9ea9de1f73d6b43ef4fe07f6b4860dc8bc0b2e7e94
  ProductCode: '{EA457B21-F73E-494C-ACAB-524FDE069978}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{EA457B21-F73E-494C-ACAB-524FDE069978}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft VS Code'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/8a7abeba6e03ea3af87bfbce9a1b7e48fed567b8/VSCodeUserSetup-arm64-1.129.1.exe
  InstallerSha256: 97176fd9ed78a5c59eb442bc425ef252005d93963eba7331e9f03ce0c7f26dc5
  ProductCode: '{D9E514E7-1A56-452D-9337-2990C0DC4310}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Visual Studio Code (User)
    ProductCode: '{D9E514E7-1A56-452D-9337-2990C0DC4310}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Microsoft VS Code'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/8a7abeba6e03ea3af87bfbce9a1b7e48fed567b8/VSCodeSetup-arm64-1.129.1.exe
  InstallerSha256: 0a5d7b0150c1c1e8ed0f826dbdb041ecee3e3693021db26ad8d227a3e3c0052f
  ProductCode: '{A5270FC5-65AD-483E-AC30-2C276B63D0AC}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{A5270FC5-65AD-483E-AC30-2C276B63D0AC}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft VS Code'
ManifestType: installer
ManifestVersion: 1.28.0