# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.OneNote
PackageVersion: 16.0.20228.20124
PackageLocale: it
ShortDescription: Il tuo blocco appunti digitale che ti consente di acquisire e organizzare i contenuti su tutti i tuoi dispositivi. Annota le tue idee, tieni traccia degli appunti delle lezioni e delle riunioni, ritaglia dal Web o crea un elenco attività.
Tags:
- 1note
- blocco-appunti-digitale
- bloccoappuntidigitale
- microsoft-one-note
- microsoft-onenote
- microsoftonenote
- xpffzhvgqwwlhb
ManifestType: locale
ManifestVersion: 1.12.0
