# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: wheremyfoodat.Panda3DS.GUI.Nightly
PackageVersion: 0.9.5aaa1d2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
