# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nvidia.Driver.GeForceGameReady
PackageVersion: "391.35"
ReleaseDate: 2018-03-27
InstallerType: exe
InstallerSwitches:
  Silent: -s -n Display.Driver HDAudio.Driver
  SilentWithProgress: -s -n Display.Driver HDAudio.Driver
  Log: -log:"<LOGPATH>"
Installers:
- Architecture: x64
  InstallerUrl: https://uk.download.nvidia.com/Windows/391.35/391.35-desktop-win10-64bit-international-whql.exe
  InstallerSha256: d352ad886b250482385ae1b597cf1be301e2e3378567e10feb8942fec0c964c2
- Architecture: x86
  InstallerUrl: https://uk.download.nvidia.com/Windows/391.35/391.35-desktop-win10-32bit-international-whql.exe
  InstallerSha256: 5128180228d63d550869d615d9d165eabbc1bc1ce1c5a8235466e16d4867cb4e
  UnsupportedOSArchitectures:
  - x64
InstallerSuccessCodes:
- 1
ExpectedReturnCodes:
- InstallerReturnCode: 3858759936
  ReturnResponse: systemNotSupported
ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
