# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: OpenAI.ChatGPT
PackageVersion: 26.930.4958.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
UpgradeBehavior: install
FileExtensions:
- csv
- docx
- pptx
- skill
- tsv
- xls
- xlsm
- xlsx
PackageFamilyName: OpenAI.Codex_2p2nqsd0c76g0
Capabilities:
- graphicsCaptureProgrammatic
- graphicsCaptureWithoutBorder
- internetClient
RestrictedCapabilities:
- localSystemServices
- packagedServices
- runFullTrust
- unvirtualizedResources
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://persistent.oaistatic.com/codex-app-prod/releases/26.930.4958.0/ChatGPT-x64.msix
  InstallerSha256: E03019134D729C6416173B0712AA5C51D079966253F77077F4BF105D29D8FCE7
  SignatureSha256: E64EAE50C5C0FA0870EB5513C822B18DACAD6AF96C6527359D37090C4A4E67C0
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/OpenAI.Codex_26.930.4958.0_x64__2p2nqsd0c76g0'
- Architecture: arm64
  InstallerUrl: https://persistent.oaistatic.com/codex-app-prod/releases/26.930.4958.0/ChatGPT-arm64.msix
  InstallerSha256: 763B6A237A024682306C97102B74468DCA89D08DA3094D86D8DC43EED89D5C93
  SignatureSha256: 77E72ED5046546BD964F331C9174AAFF3753B52CBC506AC9F607ADA5400213CB
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/OpenAI.Codex_26.930.4958.0_arm64__2p2nqsd0c76g0'
ManifestType: installer
ManifestVersion: 1.28.0
