# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.VSTOR.LanguagePack.he
PackageVersion: 10.0.60917
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /q /norestart
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/4/a/e/4aed151e-5203-4e79-bc40-45ce7626d471/vstor40_LP_x86_heb.exe
  InstallerSha256: F553E368BD7393E8D791F89342CE42BD1D5C7AE6BC918B6C2C0A02774CC89FAB
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/4/a/e/4aed151e-5203-4e79-bc40-45ce7626d471/vstor40_LP_x64_heb.exe
  InstallerSha256: D2E0220E1DC578083E24C37B1C74A5A5B2C5C21A6DD0EB24A0EA0E5AB772CC99
ExpectedReturnCodes:
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
ManifestType: installer
ManifestVersion: 1.28.0
