# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Huawei.OfficeAce
PackageVersion: 1.2.1
InstallerType: nullsoft
Scope: user
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\OfficeAce'
Installers:
- Architecture: x64
  InstallerUrl: https://res-static.hc-cdn.cn/cloudbu-site/china/zh-cn/OfficeAce/OfficeAce-1.2.1-windows-x64-setup.exe
  InstallerSha256: CC470AD2C21CA01C31C7AACB15A7373C34D5FE6398EFC44E236350F59E59F1F1
ManifestType: installer
ManifestVersion: 1.28.0
