# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Microsoft.UpdateHealthTools.W11-21H2
PackageVersion: "4.71"
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.28.0