# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Microsoft.DotNet.Runtime.10.x64
PackageVersion: 10.0.11
PackageLocale: en
Publisher: Microsoft Corporation
PackageName: Microsoft .NET Runtime 10.0 (x64 runtime on ARM64)
PackageUrl: https://dotnet.microsoft.com/en-us/download/dotnet/10.0
License: MIT
ShortDescription: .NET is a free, cross-platform, open-source developer platform for building many different types of applications.
Description: |-
  .NET is a free, cross-platform, open-source developer platform for building many different types of applications.

  This Winget package is for those who need the x64 runtime installed on ARM64 Windows 11 OS versions alongside the ARM64(/x86) runtimes. If you use a Windows x64 OS, use the normal Microsoft.DotNet.Runtime.10 package instead.
Moniker: dotnet-runtime-10-x64
Tags:
- 64-bit-runtime
- 64bitruntime
- mdnr1064
- microsoft-.net-runtime-10-x64
- microsoft-dot-net-runtime-10-x64
- microsoft.netruntime10x64
- microsoftdotnetruntime10x64
- windows-11-prism
ManifestType: defaultLocale
ManifestVersion: 1.12.0
