# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.VisualStudioCode
PackageVersion: 1.136.1
Commands:
- code
ReleaseDate: 2026-09-03
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/a44adf7f53e00964ab890f9f8758a334f1fc15bc/VSCodeUserSetup-x64-1.136.1.exe
  InstallerSha256: 6407EF106377D4BBA9883FDB6225E5D99F136A258F62F5B80EBFA6EA130B0B18
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Microsoft VS Code'
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/a44adf7f53e00964ab890f9f8758a334f1fc15bc/VSCodeSetup-x64-1.136.1.exe
  InstallerSha256: F88C83AFD2ACDA9CBFFFBD89E1EBE35A88162616F7CB2014AB11118EF91C3BFE
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{EA457B21-F73E-494C-ACAB-524FDE069978}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{EA457B21-F73E-494C-ACAB-524FDE069978}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft VS Code'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Code.exe
    PortableCommandAlias: code
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/a44adf7f53e00964ab890f9f8758a334f1fc15bc/VSCode-win32-x64-1.136.1.zip
  InstallerSha256: DECA16EA5C4D71ECE23E50AF57632BBA3ABD0E3577C3C8BFBCDD90B03F11E402
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/a44adf7f53e00964ab890f9f8758a334f1fc15bc/VSCodeUserSetup-arm64-1.136.1.exe
  InstallerSha256: 7CE1D696F44AA688BDE55E414ED270A2F5C44883590931F4B9C9FBCF79F09B06
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{D9E514E7-1A56-452D-9337-2990C0DC4310}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{D9E514E7-1A56-452D-9337-2990C0DC4310}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Microsoft VS Code'
- Architecture: arm64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/a44adf7f53e00964ab890f9f8758a334f1fc15bc/VSCodeSetup-arm64-1.136.1.exe
  InstallerSha256: 57454D84D55F07B532FCF42295C57A5445054006BE668AD7B1C19C9DE9F68E31
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{A5270FC5-65AD-483E-AC30-2C276B63D0AC}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{A5270FC5-65AD-483E-AC30-2C276B63D0AC}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft VS Code'
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Code.exe
    PortableCommandAlias: code
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/a44adf7f53e00964ab890f9f8758a334f1fc15bc/VSCode-win32-arm64-1.136.1.zip
  InstallerSha256: E46A3BA3725416A499C8FBC985FA71D1E3172A954305C31F7192C37BB5EF20FD
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
