# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.VisualStudioCode
PackageVersion: 1.136.2
Commands:
- code
ReleaseDate: 2026-09-04
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/88e44fa0e00b08f7758b4f6d05632e4fd5e4df6f/VSCodeUserSetup-x64-1.136.2.exe
  InstallerSha256: C5A0362B32FBEF66B27239211D1BDED3D1A9CF2A884949B1BA87C8F03F3A7C32
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Microsoft VS Code'
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/88e44fa0e00b08f7758b4f6d05632e4fd5e4df6f/VSCodeSetup-x64-1.136.2.exe
  InstallerSha256: BD0D3C683F2004BCAE7245855E1980C4B0EA7E3C1A4239EFB45B6927808BE6D7
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{EA457B21-F73E-494C-ACAB-524FDE069978}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{EA457B21-F73E-494C-ACAB-524FDE069978}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft VS Code'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Code.exe
    PortableCommandAlias: code
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/88e44fa0e00b08f7758b4f6d05632e4fd5e4df6f/VSCode-win32-x64-1.136.2.zip
  InstallerSha256: 7583B9F5D300BD6AC882160417D95BBD0978EBEF04FB195844243EBD9F3EBE1C
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/88e44fa0e00b08f7758b4f6d05632e4fd5e4df6f/VSCodeUserSetup-arm64-1.136.2.exe
  InstallerSha256: 5E48161BA1D0E52C4AAD7569DA66557B8F73986BE8297C4C5CD67BE700323811
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{D9E514E7-1A56-452D-9337-2990C0DC4310}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{D9E514E7-1A56-452D-9337-2990C0DC4310}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Microsoft VS Code'
- Architecture: arm64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/88e44fa0e00b08f7758b4f6d05632e4fd5e4df6f/VSCodeSetup-arm64-1.136.2.exe
  InstallerSha256: DBF40A726D71B4DDB2B35F748C74E31057EECA0464A4EBD1EC1B853070986C3B
  InstallerSwitches:
    Custom: /mergetasks=!runcode
  ProductCode: '{A5270FC5-65AD-483E-AC30-2C276B63D0AC}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{A5270FC5-65AD-483E-AC30-2C276B63D0AC}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft VS Code'
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Code.exe
    PortableCommandAlias: code
  InstallerUrl: https://vscode.download.prss.microsoft.com/dbazure/download/stable/88e44fa0e00b08f7758b4f6d05632e4fd5e4df6f/VSCode-win32-arm64-1.136.2.zip
  InstallerSha256: 3AAFD3ABB3DA735310841608684D503A688D61F9D71E98349D22CC71F3D2AFBA
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
