# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Microsoft.DotNet.Native.Framework.1.6
PackageVersion: 1.6.27413
PackageLocale: en
Publisher: Microsoft Corporation
PackageName: Microsoft .NET Native Framework 1.6
PackageUrl: https://www.nuget.org/packages/runtime.win10-x64.Microsoft.Net.Native.SharedLibrary/1.6.4
License: MIT
ShortDescription: A pre-compilation technology for building Universal Windows (UWP) applications in Visual Studio 2015 and later. Applications are automatically compiled to native code before they reach consumer devices.
Description: |-
  A pre-compilation technology for building Universal Windows (UWP) applications in Visual Studio 2015 and later. Applications are automatically compiled to native code before they reach consumer devices.

  Not to be confused with Microsoft .NET Framework or Microsoft .NET Core Framework.
Moniker: mdnf16
Tags:
- Microsoft.NET.Native.Framework.1.6
- Microsoft.NetCore
- NetCore.WindowsUniversalPlatform
- microsoft-dotnet-native-framework
- microsoftdotnetnativeframework
- microsoft-net-native-framework
- microsoftnetnativeframework
- microsoft-.net-native-framework
- microsoft.netnativeframework
- uwp-apps-dependency
- mdnnf
ManifestType: defaultLocale
ManifestVersion: 1.28.0