# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: GameJolt.GameJolt
PackageVersion: 1.39.4
PackageLocale: en
Publisher: Game Jolt Inc.
PackageName: Game Jolt Desktop App
PackageUrl: https://gamejolt.com/app
License: Freeware
ShortDescription: The client launcher of the videogame storefront Game Jolt.
Moniker: gamejolt
Tags:
- game-jolt-client
- gamejoltclient
- game-jolt-launcher
- gamejoltlauncher
- game-jolt-desktop-app
- gamejoltdesktopapp
- game-launcher
- gamelauncher
- game-client
- gameclient
- games-storefront
ManifestType: defaultLocale
ManifestVersion: 1.28.0
