# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Microsoft.DotNet.Runtime.9.x64
PackageVersion: 9.0.18
PackageLocale: en
Publisher: Microsoft Corporation
PackageName: Microsoft .NET Runtime 9.0 (x64 runtime on ARM64)
PackageUrl: https://dotnet.microsoft.com/en-us/download/dotnet/9.0
License: MIT
ShortDescription: .NET is a free, cross-platform, open-source developer platform for building many different types of applications.
Description: |-
  .NET is a free, cross-platform, open-source developer platform for building many different types of applications.

  This Winget package is for those who need the x64 runtime installed on ARM64 Windows 11 OS versions alongside the ARM64(/x86) runtimes. If you use a Windows x64 OS, use the normal Microsoft.DotNet.Runtime.9 package instead.
Moniker: dotnet-runtime-9-x64
Tags:
- microsoft-dot-net-runtime-9-x64
- microsoftdotnetruntime9x64
- microsoft-.net-runtime-9-x64
- microsoft.netruntime9x64
- 32-bit-runtime
- 32bitruntime
- mdnr964
ManifestType: defaultLocale
ManifestVersion: 1.28.0
