# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: StackHawk.HawkScan
PackageVersion: 6.4.0
ReleaseDate: 2026-08-20
InstallerType: wix
Scope: machine
UpgradeBehavior: install
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/StackHawk'
Installers:
- Architecture: x64
  InstallerUrl: https://download.stackhawk.com/hawk/6.4.0/windows-x64/hawk.msi
  InstallerSha256: E7D8387CB2CD6E0ABA6D23ED5D17C3257FF5D6DE798C2EB40A1C7D3BB5415D56
  ProductCode: '{CD22FAF5-794F-4E63-9E44-3767F9232018}'
  AppsAndFeaturesEntries:
  - ProductCode: '{CD22FAF5-794F-4E63-9E44-3767F9232018}'
    UpgradeCode: '{974BC83E-5C25-4F72-8B86-B9C0E28B26FA}'
- Architecture: arm64
  InstallerUrl: https://download.stackhawk.com/hawk/6.4.0/windows-arm64/hawk.msi
  InstallerSha256: 6476436533AA3C30A2E7BCE15BE2CD3780C72FDFC23C472B3045A66ADB478682
  ProductCode: '{5BC0774B-3D6F-41BB-82FE-9D042D016C3B}'
  AppsAndFeaturesEntries:
  - ProductCode: '{5BC0774B-3D6F-41BB-82FE-9D042D016C3B}'
    UpgradeCode: '{974BC83E-5C25-4F72-8B86-B9C0E28B26FA}'
ManifestType: installer
ManifestVersion: 1.12.0
