# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AIMP.AIMP
PackageVersion: 5.40.2724
InstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2026-08-24
Installers:
- Architecture: x64
  InstallerUrl: https://aimp.ru/files/desktop/builds/aimp_5.40.2724_w64.exe
  InstallerSha256: D77693E3BBB625EFF4FF5F2FF72315129781EC7A196BA782F3DE89BC99F2E5E5
ManifestType: installer
ManifestVersion: 1.12.0
