# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LizardByte.libvirtualhid
PackageVersion: 2026.914.1218.10
InstallerType: wix
Scope: machine
InstallModes:
- interactive
InstallerSwitches:
  InstallLocation: INSTALL_ROOT="<INSTALLPATH>"
ProductCode: '{9F7D7169-CC37-42B3-BEA6-F0C71EE947E3}'
ReleaseDate: 2026-09-14
AppsAndFeaturesEntries:
- ProductCode: '{9F7D7169-CC37-42B3-BEA6-F0C71EE947E3}'
  UpgradeCode: '{71D7B738-9D83-4E57-82E3-C3106D9F8053}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/libvirtualhid'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LizardByte/libvirtualhid/releases/download/v2026.914.1218.10/libvirtualhid-Windows-AMD64-driver-installer.msi
  InstallerSha256: BC31539A41F71939C13DECB171CCBD4306FAE1FED63273434A4F5CECCAF3E71C
ManifestType: installer
ManifestVersion: 1.12.0
