# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: inikep.lzbench
PackageVersion: '2.4'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lzbench24.exe
  PortableCommandAlias: lzbench
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/inikep/lzbench/releases/download/v2.4/lzbench24_windows_gcc13.zip
  InstallerSha256: A118772CC5A81B8CB630C6ABAFD048A796A1F5E43A3DC377D94987DC20D85315
ManifestType: installer
ManifestVersion: 1.28.0
