# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PCBPiezotronics.G4LDUtility
PackageVersion: 5.6.0.70
InstallerType: zip
NestedInstallerType: burn
NestedInstallerFiles:
- RelativeFilePath: G4Setup_v5.6.0_x64.exe
Scope: machine
ReleaseDate: 2026-06-24
AppsAndFeaturesEntries:
- ProductCode: '{BC98A1A0-A64D-4F67-B257-A2B4DC4D2EBE}'
  UpgradeCode: '{BE747F75-777A-4B4E-AAB2-02DA78FD5D98}'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PCB Piezotronics\G4'
Installers:
- Architecture: x64
  InstallerUrl: https://www.larsondavis.com/ContentStore/mktg/LD_Software/G4Setup_v5.6.0_x64.zip
  InstallerSha256: 2EF0584594467B8C3A0DC37B6F5114D511B5BEE5C3FE5F76348EEBF981EEE04A
ManifestType: installer
ManifestVersion: 1.12.0
