# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nvidia.Driver.GeForceGameReady
PackageVersion: "610.62"
ReleaseDate: 2026-06-16
InstallerType: exe
InstallerSwitches:
  Silent: -s -n Display.Driver HDAudio.Driver
  SilentWithProgress: -s -n Display.Driver HDAudio.Driver
  Log: -log:"<LOGPATH>"
Installers:
- Architecture: x64
  InstallerUrl: https://uk.download.nvidia.com/Windows/610.62/610.62-desktop-win10-win11-64bit-international-dch-whql.exe
  InstallerSha256: dfe395bbc971825cf30884bc49990a7527b9da72f8df947fb9f196265712d5a5
InstallerSuccessCodes:
- 1
ExpectedReturnCodes:
- InstallerReturnCode: 3858759936
  ReturnResponse: systemNotSupported
ProductCode: "{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"
AppsAndFeaturesEntries:
- DisplayVersion: "610.62"
  ProductCode: "{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"
  Publisher: NVIDIA Corporation
ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0