# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: Flirc.SkipApp
PackageVersion: 0.9.995.10457
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
