# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: KDE.Merkuro
PackageVersion: '6687'
PackageLocale: en-US
Publisher: KDE
PackageName: Merkuro
PackageUrl: https://apps.kde.org/merkuro/
License: GPL-2.0-or-later
ShortDescription: A calendar and contact application that allows you to manage your tasks, events and contacts. It supports both local calendars as well as a multitude of online calendars.
Moniker: merkuro
ManifestType: defaultLocale
ManifestVersion: 1.28.0
