# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.Outlook
PackageVersion: 1.2026.728.100
PackageLocale: ja
PackageUrl: https://support.microsoft.com/da-dk/outlook/getstarted/getting-started-with-the-new-outlook-for-windows
ShortDescription: 新しい Outlook for Windows は、Windows を使用するすべてのユーザーが無料で利用できるクラス最高のメール エクスペリエンスです。
Tags:
- e-mails
- microsoft-outlook-for-windows
- ms-outlook
- new-outlook
- かれんだー
- まいくろそふとあうとるっくのうぃんどうず
- めーる
- カレンダー
- マイクロソフトアウトルックノウィンドウズ
- メール
- 新アウトルック
- 暦
ManifestType: locale
ManifestVersion: 1.12.0
