# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Hytto.LovenseRemote
PackageVersion: 1.40.0
PackageLocale: en-US
Publisher: Hytto Ltd.
PackageName: Lovense Remote
License: Proprietary
ShortDescription: A companion app for controlling Lovense devices
Moniker: lovense-remote
ManifestType: defaultLocale
ManifestVersion: 1.28.0
