# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Buypass.Javafri
PackageVersion: 1.4.1.16
PackageLocale: nb
Publisher: Buypass
PackageName: Buypass Javafri
PackageUrl: https://www.buypass.no/hjelp/buypass-id/smartkort/javafri
License: Proprietær
ShortDescription: En programvareløsning som muliggjør sikker kommunikasjon mellom nettleseren og Buypass Smartkort. Løsningen benyttes av en rekke av Buypass sine brukersteder samt i Buypass sine autentiseringstjenester.
Moniker: buypass
Tags:
- buypass-id
- buypass-javafri
- buypass-scproxy
- buypass-smartkort
- buypassjavafri
- buypasssmartkort
- id-porten
- idporten
- norge
ManifestType: defaultLocale
ManifestVersion: 1.12.0
