# Created by Anthelion using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Linkly.Linkly
PackageVersion: 5.11.9
InstallerType: inno
Scope: machine
InstallModes:
- interactive
UpgradeBehavior: install
ProductCode: PC-EFTPOS_is1
ReleaseDate: 2026-09-10
AppsAndFeaturesEntries:
- ProductCode: PC-EFTPOS_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PC_EFT'
Installers:
- Architecture: x86
  InstallerUrl: https://linklydownloads.z8.web.core.windows.net/installer/5.11.9/Linkly%20Setup.exe
  InstallerSha256: 4F6E60F31CB48C2E5B4BAD766B21A74C4E528CC39352B1BD538CC1F8D240A7ED
ManifestType: installer
ManifestVersion: 1.12.0
