# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.VSTOR.LanguagePack.fi
PackageVersion: 10.0.60917
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /q /norestart
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VSTOR
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/4/a/e/4aed151e-5203-4e79-bc40-45ce7626d471/vstor40_LP_x86_fin.exe
  InstallerSha256: 8F3A628C673D2C77C7A203E01AB6FFB7C0D4AD1CA837D795A2447E0F985C0E6B
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/4/a/e/4aed151e-5203-4e79-bc40-45ce7626d471/vstor40_LP_x64_fin.exe
  InstallerSha256: 8135812A108B17B06B6382F9A397C9E54751F6F985A34D3DD293BF6DE2976C9B
ExpectedReturnCodes:
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
ManifestType: installer
ManifestVersion: 1.28.0
