# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json

PackageIdentifier: SiliconLaboratories.CP210x.VCP
PackageVersion: "6.7"
PackageLocale: nb-NO
PackageName: Windows-driverpakke - Silicon Laboratories (silabenm) Ports
ShortDescription: «CP210x VCP Windows»-driveren.
ManifestType: locale
ManifestVersion: 1.28.0
