name: publish

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish.yml'
      - 'index/**'
      - 'manifests/**'
      - 'fonts/**'
  workflow_dispatch:
  workflow_call:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  merge:
    name: Merge Manifests
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Merge manifests
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./.github/workflows/merge.ps1

      - parallel:
          - name: Upload merged manifests
            uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
            with:
              name: merged-manifests
              path: ${{ runner.temp }}/manifests/*.yaml
              if-no-files-found: error

          - name: Upload index
            uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
            with:
              name: index
              path: index
              if-no-files-found: error

  publish:
    name: Publish Manifests
    needs: merge
    runs-on: windows-2025
    permissions:
      id-token: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout mise configuration
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          sparse-checkout: |
            mise.lock
            mise.toml
          sparse-checkout-cone-mode: false

      - parallel:
          - name: Download index
            uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
            with:
              name: index
              path: index

          - name: Download merged manifests
            uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
            with:
              name: merged-manifests
              path: ${{ runner.temp }}/manifests

          - name: Download IndexCreationTool
            shell: bash
            run: |
              gh release download --repo pl4nty/winget-pkgs-selfhost --pattern AppInstallerCLIE2ETests.zip
              7z x ./AppInstallerCLIE2ETests.zip -o"./index" -y
            env:
              GITHUB_TOKEN: ${{ github.token }}

          - name: Setup rclone
            uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
            with:
              version: 2026.7.6
              install_args: rclone

      - parallel:
          - name: Setup and run IndexCreationTool
            working-directory: index
            run: |
              $version = Get-Date -Format yyyy.M.d.hm
              (Get-Content -Path AppxManifest.xml) -replace "<VERSION>", $version | Set-Content -Path AppxManifest.xml
              .\AppInstallerCLIE2ETests\IndexCreationTool.exe -f source.json
            env:
              TEMP: ${{ runner.temp }}

          - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
            if: github.ref == 'refs/heads/main'
            with:
              client-id: ${{ vars.AZURE_CLIENT_ID }}
              tenant-id: ${{ vars.AZURE_TENANT_ID }}
              subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

          - name: Install AzureSignTool
            run: dotnet tool install --global AzureSignTool

      - name: Sign source package
        working-directory: index
        if: github.ref == 'refs/heads/main'
        run: |
          $msixFiles = Get-ChildItem cache -Recurse -Filter *.msix | Select-Object -ExpandProperty FullName
          AzureSignTool sign -kvu $env:KEY_VAULT_URL -kvc $env:KEY_VAULT_CERT -kvm -tr http://timestamp.acs.microsoft.com -td sha256 -fd sha256 $msixFiles
        env:
          KEY_VAULT_URL: ${{ vars.KEY_VAULT_URL }}
          KEY_VAULT_CERT: ${{ vars.KEY_VAULT_CERT }}

      - name: Publish source
        working-directory: index
        run: rclone sync cache r2:winget-extras/cache --checksum --fast-list ${{ github.ref != 'refs/heads/main' && '--dry-run' || '' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ENV_AUTH: 'true'
          RCLONE_CONFIG_R2_ENDPOINT: https://20e0944718a914755e926a8ac51178d7.r2.cloudflarestorage.com
