# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: DualSenseClient.DualSenseClient
PackageVersion: 1.0.0-12
PackageLocale: en-US
Publisher: DualSenseClient
PublisherUrl: https://github.com/DualSenseClient
PublisherSupportUrl: https://github.com/DualSenseClient/DualSenseClient/issues
PackageName: DualSenseClient
PackageUrl: https://github.com/DualSenseClient/DualSenseClient
License: GPL-3.0-only
LicenseUrl: https://github.com/DualSenseClient/DualSenseClient/blob/main/LICENSE
ShortDescription: Unlock the full DualSense experience on Windows & Linux.
Description: 'Unofficial DualSense client for Windows. Customize and monitor your PS5 DualSense controller: lighting, profiles, input monitoring, rumble, adaptive triggers, and audio to the controller''s speaker and haptics.'
Moniker: dualsenseclient
Tags:
- adaptive-triggers-pc
- controller-emulation
- csharp
- dotnet
- dualsense
- gamepad
- gamepad-mapper
- haptics
- playstation-5
- ps5
- sony-dualsense
- virtual-controller
ReleaseNotesUrl: https://github.com/DualSenseClient/DualSenseClient/releases/tag/v1.0.0-12.39ce5b9
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://dualsenseclient.github.io/DualSenseClient/
ManifestType: defaultLocale
ManifestVersion: 1.28.0
